//
// DisruptionDelayType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DisruptionDelayType: String, Codable, CaseIterable {
    case noDelays = "No Delays"
    case minorDelays = "Minor Delays"
    case severeDelays = "Severe Delays"
    case plannedClosure = "Planned Closure"
}
