//
// Disruption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Disruption: Codable {

    public var description: String?
    public var created: Date?
    public var lastUpdate: Date?
    public var affectedRoutes: [LineRoute]?
    public var closureText: String?
    public var delayType: DisruptionDelayType?

}
