//
// InternalStopPointProperty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InternalStopPointProperty: Codable {

    public var category: String?
    public var key: String?
    public var value: String?

}
