//
// JourneyLegPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyLegPath: Codable {

    public var lineString: String?
    public var stopPoints: [StopPoint]?
    public var linePaths: [[Float]]?

}
