//
// JourneyDateType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum JourneyDateType: String, Codable, CaseIterable {
    case arriveAt = "Arrive At"
    case departAt = "Depart At"
}
