//
// JourneyLegPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyLegPath: Codable {
    
    /// The StopPoints traveled through in this leg
    public var stopPoints: [StopPoint]?

}
