//
// JourneyMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyMode: Codable {

    public var id: String?
    public var name: String?
    public var type: String?

}
