//
// JourneyLegPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The Stop Points passed through in this leg
public struct JourneyLegPath: Codable {
    
    /// The StopPoints traveled through in this leg
    public var stopPoints: [StopPoint]?
    
    public init(stopPoints: [StopPoint]? = nil) {
        self.stopPoints = stopPoints
    }

}
