//
// JourneyLegInstruction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The instruction for the current leg of the journey
public struct JourneyLegInstruction: Codable {

    /// A summary sentence
    public var summary: String?
    
    /// A more detailed instruction
    public var detailed: String?
    
    public init(summary: String? = nil, detailed: String? = nil) {
        self.summary = summary
        self.detailed = detailed
    }

}
