//
// JourneyLegRouteOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The directions, name, and line identifier of this leg of the journey
public struct JourneyLegRouteOption: Codable {

    /// The name of the route
    public var name: String?
    
    /// The direction of the route
    public var directions: [String]?
    
    /// Basic information on the Line of this route
    public var lineIdentifier: Line?

    public init(name: String? = nil, directions: [String]? = nil, lineIdentifier: Line? = nil) {
        self.name = name
        self.directions = directions
        self.lineIdentifier = lineIdentifier
    }
}
