//
// Journey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Journey: Codable {

    public var startDateTime: Date?
    public var arrivalDateTime: Date?
    public var duration: Int?
    public var legs: [JourneyLeg]?
    
}
