//
// JourneyLegInstruction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyLegInstruction: Codable {

    public var summary: String?
    public var detailed: String?

}
