//
// JourneyMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// The mode of this journey i.e. 'elizabeth-line'
public struct JourneyMode: Codable {
    
    /// The id of the mode, i.e. elizabeth-line
    public var id: String?
    
    /// The name of the mode, usually the same as id (or a friendly version of it)
    public var name: String?
    
    /// Usually 'Mode'
    public var type: String?
    
    public init(id: String? = nil, name: String? = nil, type: String? = nil) {
        self.id = id
        self.name = name
        self.type = type
    }

}
