//
// JourneyLegRouteOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyLegRouteOption: Codable {

    public var name: String?
    public var directions: [String]?
    public var lineIdentifier: Line?

}
