//
// JourneyLegInstruction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JourneyLegInstruction: Codable {

    
    /// A summary sentence
    public var summary: String?
    
    /// A more detailed instruction
    public var detailed: String?

}
