//
// LineModeGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineModeGroup: Codable {

    public var modeName: String?
    public var lineIdentifier: [String]?

}
