//
// LineRoute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineRoute: Codable {

    public var id: String?
    public var name: String?
    public var direction: String?
    public var originationName: String?
    public var destinationName: String?

}
