//
// LineMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A mode of transport operating under TfL. i.e. tube, nationalRail, bus etc.
public enum LineMode: String, Codable, CaseIterable {
   
    public static var allCases: [LineMode] { [.tube, .bus, .dlr, .nationalRail, .overground, .replacementBus, .elizabethLine, .cableCar, .tram] }
    
    case tube = "tube"
    case bus = "bus"
    case dlr = "dlr"
    case nationalRail = "national-rail"
    case overground = "overground"
    
    @available(*, deprecated, renamed: "elizabethLine", message: "'tflrail' is deprecated and no longer a running service, it has been replaced with the Elizabeth Line")
    case tflrail = "tflrail"
    
    case replacementBus = "replacement-bus"
    case elizabethLine = "elizabeth-line"
    case cableCar = "cable-car"
    case tram = "tram"
    
    case unknown = "unknown"
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let string = try container.decode(String.self)
        self = LineMode(rawValue: string) ?? .unknown
    }
}
