//
// LineStatusValidityPeriod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineStatusValidityPeriod: Codable {

    public var fromDate: Date?
    public var toDate: Date?
    public var isNow: Bool?

}
