//
// LineMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LineMode: String, Codable, CaseIterable {
    case tube = "tube"
    case bus = "bus"
    case dlr = "dlr"
    case nationalRail = "national-rail"
    case overground = "overground"
    case tflrail = "tflrail"
    case replacementBus = "replacement-bus"
}
