//
// Line.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A line is a specific line operating under a LineMode. I.e. 'bakerloo' etc for tube, but just national-rail for nationalRail
public struct Line: Codable {
    
    /// The id of the Line
    public var id: String?
    
    /// The name of the line, i.e. 'Bakerloo'
    public var name: String?
    
    /// The name of the mode this line travels on, i.e. 'tube'
    public var modeName: String?
    
    /// Any disruptions affecting this line
    public var distruptions: [Disruption]?
    
    /// The current status of this line
    public var currentStatus: LineStatus?

}
