//
// LineStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineStatus: Codable {

    public var id: String?
    public var lineId: String?
    public var statusSeverity: Int?
    public var statusSeverityDescription: String?
    public var reason: String?
    public var created: Date?
    public var validityPeriods: [LineStatusValidityPeriod]?
    public var disruption: Disruption?

}
