//
// LineModeGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineModeGroup: Codable {
    
    /// The name of the mode i.e. 'tube'
    public var modeName: String?
    
    /// A list of line identifiers here for this moe
    public var lineIdentifier: [String]?

}
