//
// Line.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Line: Codable {

    public var id: String?
    public var name: String?
    public var modeName: String?
    public var distruptions: [Disruption]?
    public var lineStatuses: [LineStatus]?
    public var currentStatus: LineStatus?

}
