//
// LineModeGroupStatusType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A friendly text to display for LineMode status
public enum LineModeGroupStatusType: String, Codable, CaseIterable {
    case allGood = "All lines are reporting Good Service"
    case mostGood = "Most lines are reporting Good Service"
    case someProblems = "Some lines are reporting problems"
    case manyProblems = "Many lines are reporting problems"
    case allProblems = "All lines are reporting problems"
    case unk = "Unable to determine service status."
}
