//
// Point.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class Point: Codable {

    public var lat: Float?
    public var lon: Float?

    public init(lat: Float? = nil, lon: Float? = nil) {
        self.lat = lat
        self.lon = lon
    }

}
