//
// Point.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class Point: Codable {
    
    public enum PointType: String, Codable {
        case StopPoint = "Stop", POIPoint = "POI"
    }

    /// The latitude coordinate of the Point as a decimal value
    public var lat: Float?
    
    /// The longitude coordinate of the Point as a decimal value
    public var lon: Float?
    
    /// The type of Point
    public var pointType: PointType?

    public init(lat: Float? = nil, lon: Float? = nil, pointType: PointType? = nil) {
        self.lat = lat
        self.lon = lon
        self.pointType = pointType
    }
}

enum PointFamily: String, ClassFamily {
    
    case POI = "POI"
    case Stop = "Stop"
    
    static var discriminator: Discriminator = .PointDiscriminator
    
    func getType() -> AnyObject.Type {
        switch self {
        case .Stop:
            return StopPoint.self
        case .POI:
            return POIPoint.self
        }
    }
}
