//
// StopPointProperty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Additional properties for a StopPoint, i.e. whether a StopPoint has WiFi or not
public struct StopPointProperty: Codable {

    /// The name of the property, i.e. 'WiFi'
    public var name: String?
    
    /// The value of the property, i.e. 'Yes'
    public var value: String?
    
    public init(name: String? = nil, value: String? = nil) {
        self.name = name
        self.value = value
    }
}
