//
// StopPointArrivalPlatformGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StopPointArrivalPlatformGroup: Codable {

    public var platformName: String?
    public var direction: String?
    public var arrivals: [StopPointArrival]?

}
