//
// StopPointArrivalLineGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StopPointArrivalLineGroup: Codable {

    public var lineName: String?
    public var platformGroups: [StopPointArrivalPlatformGroup]?

}
