//
// StopPointArrival.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StopPointArrival: Codable {

    public var vehicleId: String?
    public var id: String?
    public var lineId: String?
    public var lineName: String?
    public var platformName: String?
    public var direction: String?
    public var destinationName: String?
    public var timeToStation: Int?
    public var currentLocation: String?
    public var stationName: String?
    public var towards: String?
    
}
