//
// StopPointProperty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StopPointProperty: Codable {

    public var name: String?
    public var value: String?
    
}
