//
// StopPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class StopPoint: Point {

    public var icsId: String?
    public var modes: [String]?
    public var zone: String?
    public var id: String?
    public var name: String?
    public var commonName: String?
    public var lineModeGroups: [LineModeGroup]?
    public var additionalProperties: [InternalStopPointProperty]?
    public var children: [StopPoint]?
    public var properties: [StopPointProperty]?
    public var childStationIds: [String]?
}
