//
// StopPointArrivalLineGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// A collection of StopPointArrivalPlatformGroups collected under a lineName
public struct StopPointArrivalLineGroup: Codable {
    
    /// The name of the line the arrivals are for
    public var lineName: String?
    
    /// An array of platforms with arrivals attached
    public var platformGroups: [StopPointArrivalPlatformGroup]?

}
